### ISSUE TITLE
Updating configuration has strange cursor behaviour 

### ISSUE THREAD

**Issue by MarkRiddoch** [foglamp/foglamp-gui#106]
## Long story short

Updating a configuration item mid-word, i.e. not at the end of the text box is difficult because every time you enter a character in the text box the text cursor moves to the end of the text in the box

## Expected behaviour

Should be able to insert text at any point in the text box and not have the cursor jump to the end of the text after every  character you type.

## Actual behaviour

The text cursor jumps to end of the text on every character typed.

## Steps to reproduce

Take a configuration, such as the OMF north URL and try to change the hostname part of the URL whilst leaving the existing text for the path

## Your environment

GUI running on MacOS with FogLAMP on Raspberry Pi. Browser used is Safari

**Comment by praveen-garg** [comment]
@monika-Dianomic this is reproducible on **Safari (Version 11.0.3)/ macOS 10.13.3 High Sierra**. However works fine on Firefox and chrome. Please investigate and provide a fix. 

Thanks for reporting @MarkRiddoch
