### ISSUE TITLE
No scroll bars when configuration options wider than the Window

### ISSUE THREAD

**Issue by MarkRiddoch** [foglamp/foglamp-gui#12]
In the Configuration tab if the number of configuration items means the display needs to be wider than the current window width the pane can be scrolled. However there is no indication that there is invisible content on the pane. Either we should have scrollbars or some other kind of indication or we should wrap the panes to fit the window.

**Comment by praveen-garg** [comment]
We may force to make scrollbars always visible.

**Comment by praveen-garg** [comment]
**update:** This issue is specific to macOS and default behavior. Not reproducible on Windows 7/ 10 or Ubuntu based Firefox/ Chrome browsers.

**Comment by praveen-garg** [comment]
for safari: https://discussions.apple.com/thread/4322675

**Comment by praveen-garg** [comment]
Also, Config page has new design now.
