### ISSUE TITLE
"Test connection" does not work when authentication is mandatory & allowPing is False

### ISSUE THREAD

**Issue by ashish-jabble** [foglamp/foglamp-gui#147]
## Steps to reproduce
1) foglamp start

2) Set authentication as mandatory 

> curl -X PUT -H "Content-Type: application/json" -d '\{"value": "mandatory"\}' http://localhost:8081/foglamp/category/rest_api/authentication | jq

3) Set allowPing is false

> curl -X PUT -H "Content-Type: application/json" -d '\{"value": "false"\}' http://localhost:8081/foglamp/category/rest_api/allowPing | jq

4) foglamp stop

5) Re-start server again -- foglamp start 

6) Under settings menu, click on Test connection. 

## Expected behaviour
It should return ping info

## Actual behaviour
Forbidden request

**Comment by praveen-garg** [comment]
You will see 403 | forbidden as expected!
